### ISSUE TITLE
404 on all media URL's

### ISSUE THREAD

**Issue by Sil-B** [AbsoluteCommerce/Magento2-CacheBust#1]
Hi, 

Im using the CacheBust module on Magento 2.1.6. 

- I've added the apache configuration
- Enabled the module
- Busted the cache (System > Cache Management)

Problem: I'm getting a 404  on all /media/ URL's. The /static/ URL's work as expected. 

Any thoughts on how to solve this? 

Thanks, 

Sil

**Comment by josephmcdermott** [comment]
Hi @Sil-B, please send an email to support@absolutecommerce.co.uk and include what URL your media assets are attempting to load on, to try and ascertain if some config may be wrong with config.

The fact the static part is working makes me suspect it could be apache config related, as Magento 2 ships with a working example for static content, so please include your apache config also.

Kind regards,
Joseph

**Comment by Sil-B** [comment]
Thanks for the support @josephmcdermott everything works as expected!
