### ISSUE TITLE
Module is enabled but not showing in admin

### ISSUE THREAD

**Issue by conflicker** [AbsoluteCommerce/Magento2-CacheBust#2]
With Magento 2.1.7, installation of the module went smoothly. However, the module can't be seen in Stores->configuration->Advanced->Advanced

Upon checking in CLI, the module is enabled, the consle command is presented.
Any idea?

**Comment by josephmcdermott** [comment]
Hi there, sorry for the delay getting back to you.

If you can see the commands in the CLI and you can see the buttons under System > Cache Management, then you're good to go.
