### ISSUE TITLE
2.2.0

### ISSUE THREAD

**Issue by gewaechshaus** [AbsoluteCommerce/Magento2-CacheBust#4]
Hey,

thanks for developing this module... Is there a timeline when the 2.2.0 compatibility will be realized?

Greetings
Jan

**Comment by josephmcdermott** [comment]
Hi there,

It looks like Magento changed their Plugin implementation on this area, so we have made an update to match the same change. We have created a branch `bug/2.2.x-compatibility` which should resolve the issue and work with Magento 2.2.x, but will make the module backward incompatible so we are reluctant to create a new release just yet before some more investigation and testing.

If you are in a hurry you can pull that version and test yourself, and let us know if you come across any issues.

Kind regards,
Joseph

**Comment by josephmcdermott** [comment]
Version 3.0.0 is now available which supports Magento 2.2.x
