### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Absolute\CacheBust\Plugin\Signature::aroundGetBaseUrl() in

### ISSUE THREAD

**Issue by naseemqota** [AbsoluteCommerce/Magento2-CacheBust#7]
After running this command 
php bin/magento indexer:reindex

i got this error:

PHP Fatal error:  Uncaught Error: Call to undefined method Absolute\CacheBust\Plugin\Signature::aroundGetBaseUrl() in

**Comment by josephmcdermott** [comment]
Which version of this extension are you running, and which Magento version are you running?

Plugin `aroundGetBaseUrl` was replaced with `afterGetBaseUrl` in Magento 2.2.0: https://github.com/AbsoluteCommerce/Magento2-CacheBust/commit/b25457389aab4e729a6058a4df5be9e3a6db39b1#diff-c951efc80dc01fe68789cf86ca8e9856

When you review the file `vendor/absolute/magento2-cache-bust/Plugin/Signature.php` does the method `aroundGetBaseUrl` exist?

**Comment by naseemqota** [comment]
Magento -v  2.1.3

php 7.0.30

**Comment by naseemqota** [comment]
vendor/absolute/magento2-cache-bust/Plugin/Signature.php this is exist

**Comment by naseemqota** [comment]
2.2.0

"Which version of this extension are you running"

**Comment by naseemqota** [comment]
i have tried 3 branches all are having same issue.

my Magento 2.1.3
Php 7.0.30

**Comment by naseemqota** [comment]
> When you review the file vendor/absolute/magento2-cache-bust/Plugin/Signature.php does the method aroundGetBaseUrl exist 

aroundGetBaseUrl  this is not exist

**Comment by josephmcdermott** [comment]
This extension does not have a `v2.2.0`.

From Readme.md:

> For Magento 2.2.x and later please use version 3.x.x of this extension.
For earlier Magento versions, please use version 2.x.x of this extension.

Maybe try `v2.2.3`, as you can see, `v2.2.3` of this extension does have the `aroundGetBaseUrl`:
https://github.com/AbsoluteCommerce/Magento2-CacheBust/blob/2.3.3/Plugin/Signature.php#L32

Failing that, please try upgrading to the latest version of Magento 2.2.5 and the latest version of this extension.

**Comment by ghost** [comment]
Hi ,
I am also getting the same error

PHP Fatal error: Uncaught Error: Call to undefined method Absolute\CacheBust\Plugin\Signature::aroundGetBaseUrl() 

my Magento 2.1.10
Php 7.0.30

Can you please suggest me from where should I download extension for Magento 2.1.10

**Comment by josephmcdermott** [comment]
I've tried installing Absolute_CacheBust on `Magento 2.1.10` with `PHP 7.0.22`. Using `Absolute CacheBust 3.1.0` gives your fatal error, as expected. Using `Absolute CacheBust 2.3.3` does not, as expected. This is the reason for the line in the README.md:

> For Magento 2.2.x and later please use version 3.x.x of this extension.
For earlier Magento versions, please use version 2.x.x of this extension.

So for earlier versions of Magento than 2.2.x, which applies to you both:

```
$ composer require absolute/magento2-cache-bust 2.3.3
```

If you've already installed a later version, you'll want to delete the module entry from the database so it will drop the version down, otherwise you'll get errors of a version mismatch on the frontend:

```
mysql > delete from setup_module where module = 'Absolute_CacheBust';
```

After which you should run `./bin/magento setup:upgrade` once more to install the lower version.

**Comment by naseemqota** [comment]
@gaurid-iprogrammer  you have downloaded wrong plugin let me send you the link download this and will get no error.

download this one  

https://github.com/AbsoluteCommerce/Magento2-CacheBust/tree/2.3.3

**Comment by ghost** [comment]
@nasimqota yes. Now it's working fine. thank you!
